### ISSUE TITLE
salut c'est quelqu'un que tu connais, dans ta classe de 2de, ajoute un moyen de contact sur ton profil

### ISSUE THREAD

**Issue by toythebananaman** [lechatdelasorciere/merci#1]
# Problems:
Va sur [Github dashboard](https://github.com/dashboard), pour ajouter une description sur ton profile et pour pouvoir te contacter, sinon ceci est la seule possibilité, ajoute un discord ou mail.

**Comment by toythebananaman** [comment]
done bruh

**Comment by lechatdelasorciere** [comment]
A quoi ça sert? Tu aurait pu corriger les fautes d'orthographe à la place. Je te remercie par avance.

**Comment by lechatdelasorciere** [comment]
Peut être dans le futur mais je dois d'abord corriger les fautes de français . De plus je veux pas être spammé. Donc je pense que je vais créer un moyen de discuter sans créer de "Issues"

**Comment by toythebananaman** [comment]
arrete de l'ouvrir encore
